name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install
        
      - name: Commit local changes (if any)
        run: |
          git add package-lock.json
          git commit -m "Fix package-lock changes" || echo "No changes to commit"

      - name: Compile TypeScript
        run: npm run compile

      - name: Commit and push compiled files to 'compiled' branch
        run: |
          # Créer une branche 'compiled' qui n'a que les fichiers compilés
          git switch --orphan compiled
          git reset --hard

          # Ajouter et commit les fichiers compilés dans 'dist'
          git add dist
          git commit -m "Compiled TypeScript to JavaScript"

          # Push sur la branche 'compiled'
          git push origin compiled --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
